### ISSUE TITLE
执行 install.sh 时报错

### ISSUE THREAD

**Issue by zhangnew** [sjdy521/Mojo-ActivePerl#1]
`env: perl/bin/perl: No such file or directory
`

perl/bin/perl 这个文件是存在的

**Comment by hexsum** [comment]
是在哪个目录下执行install.sh的

发自 网易邮箱大师
在2016年06月10日 00:11，zhangnew 写道:

env: perl/bin/perl: No such file or directory

perl/bin/perl 这个文件是存在的

**Comment by zhangnew** [comment]
`/root/webqq/Mojo-ActivePerl-master`
`/root/webqq/ActivePerl-5.22.1.2201-x86_64-linux-glibc-2.15-299574`

解压后进入Mojo-ActivePerl-master目录下，然后下载官方的也一样，把 install.sh 中的 perl 路径改成绝对路径依然不行

**Comment by hexsum** [comment]
能不能把整个命令操作执行步骤尽量都发出来我看下，如果执行方式正确，这个报错就有点奇怪

发自 网易邮箱大师
在2016年06月10日 09:26，zhangnew 写道:

/root/webqq/Mojo-ActivePerl-master
/root/webqq/ActivePerl-5.22.1.2201-x86_64-linux-glibc-2.15-299574

解压后进入Mojo-ActivePerl-master目录下，然后下载官方的也一样，把 install.sh 中的 perl 路径改成绝对路径依然不行

**Comment by zhangnew** [comment]
我也觉得非常奇怪，Google`“env: perl/bin/perl: No such file or directory”`只有4个结果，没看到解决办法。
我是完全按照 README 文档做的，root用户，到第三步出现的问题。
是不是和当前的 perl 版本有关？`This is perl, v5.10.1 (*) built for i386-linux-thread-multi`

**Comment by hexsum** [comment]
你用的是什么系统？

发自 网易邮箱大师
在2016年06月10日 09:39，zhangnew 写道:

我也觉得非常奇怪，Google“env: perl/bin/perl: No such file or directory”只有4个结果，没看到解决办法。
我是完全按照 README 文档做的，到第三步出现的问题。
是不是和当前的 perl 版本有关？This is perl, v5.10.1 (*) built for i386-linux-thread-multi

**Comment by zhangnew** [comment]
VPS，Centos 6.6 x86 minimal  重新看了下README ，系统要求Unix/Linux x86_64，看来是系统的问题

**Comment by hexsum** [comment]
最好可以我远程亲自看一下
或者不用这个activeperl好了 自己单独编译安装个 下载perl官方源码 然后configure make && make install 也是挺快的

发自 网易邮箱大师
在2016年06月10日 09:48，zhangnew 写道:

VPS，Centos 6.6 x86 minimal

**Comment by zhangnew** [comment]
谢谢。源码包安装成功了，然后换了 centos 7 x86_64 可以直接执行 install.sh 安装了。
然后执行`cpanm Mojo::Webqq`时候报错：

```
cpanm (App::cpanminus) 1.7040 on perl 5.022001 built for x86_64-linux-thread-multi
Work directory is /root/.cpanm/work/1465526110.762
You have LWP 6.13
You have /usr/bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Mojo::Webqq () on cpanmetadb ...
--> Working on Mojo::Webqq
Fetching http://www.cpan.org/authors/id/S/SJ/SJDY/Mojo-Webqq-1.8.0.tar.gz
-> OK
Unpacking Mojo-Webqq-1.8.0.tar.gz
Entering Mojo-Webqq-1.8.0
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.04_01)
Configuring Mojo-Webqq-v1.8.0
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Mojo::Webqq
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04_01)
Checking if you have Encode::Locale 0 ... Yes (1.05)
Checking if you have Time::Piece 0 ... Yes (1.31)
Checking if you have IO::Socket::SSL 1.94 ... Yes (2.020)
Checking if you have Mojolicious 6.11 ... Yes (6.57)
Checking if you have Time::Seconds 0 ... Yes (1.31)
Checking if you have Time::HiRes 0 ... Yes (1.9726)
-> FAIL Can't configure the distribution. You probably need to have 'make'. See /root/.cpanm/work/1465526110.762/build.log for details.
```

上面就是`/root/.cpanm/work/1465526110.762/build.log`的内容，没看到报错信息。不知道要在哪里执行 `make`

因为 Mojo-ActivePerl 已经集成了 Mojo-Webqq，可能是升级出错吧，目前能够使用，先这样把，谢谢！
