### ISSUE TITLE
按之前需要升级系统glibc到2.15+版本

### ISSUE THREAD

**Issue by zjcnew** [sjdy521/Mojo-ActivePerl#2]
cd /usr/src/
wget http://ftp.gnu.org/gnu/glibc/glibc-2.15.tar.bz2
tar jxf glibc-2.15.tar.bz2
mkdir glibc-2.15/build
cd glibc-2.15/build
../configure --prefix=/usr
make && make install

**Comment by hexsum** [comment]
没看到问题是什么
